export const EXAM_CATEGORIES = [
  "SAT",
  "ACT",
  "AP Classes",
  "LSAT",
  "MCAT",
  "GMAT",
  "USMLE (Steps 1-3)",
  "COMLEX-USA",
  "NCLEX-RN/PN",
  "BAR Exam",
];

export const AP_CLASSES = [
  "AP Art History",
  "AP Music Theory",
  "AP Studio Art: 2-D Design",
  "AP Studio Art: 3-D Design",
  "AP Studio Art: Drawing",
  "AP English Language and Composition",
  "AP English Literature and Composition",
  "AP Comparative Government and Politics",
  "AP European History",
  "AP Human Geography",
  "AP Macroeconomics",
  "AP Microeconomics",
  "AP Psychology",
  "AP United States Government and Politics",
  "AP United States History",
  "AP World History: Modern",
  "AP Calculus AB",
  "AP Calculus BC",
  "AP Computer Science A",
  "AP Computer Science Principles",
  "AP Statistics",
  "AP Biology",
  "AP Chemistry",
  "AP Environmental Science",
  "AP Physics 1: Algebra-Based",
  "AP Physics 2: Algebra-Based",
  "AP Physics C: Electricity and Magnetism",
  "AP Physics C: Mechanics",
  "AP Chinese Language and Culture",
  "AP French Language and Culture",
  "AP German Language and Culture",
  "AP Italian Language and Culture",
  "AP Japanese Language and Culture",
  "AP Latin",
  "AP Spanish Language and Culture",
  "AP Spanish Literature and Culture",
];
